apiVersion: v1
kind: Service
metadata:
  name: new-webservice
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000
  selector:
    app: employees
    version: v2
