apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app.kubernetes.io/name: webapp
spec:
  containers:
  - name: webapplication-container
    image: 967553690170.dkr.ecr.us-east-1.amazonaws.com/newapp:v0.2
    ports:
    - containerPort: 8080
    env:
      - name: DBHOST
        value: 10.244.0.13
      - name: DBPORT
        value: "3306"
      - name: DBPWD
        value: "tarun"
